TrainingArguments:
  num_train_epochs: 0.01
  warmup_steps: 50
  per_device_train_batch_size: 1
  weight_decay: 0.01
  logging_steps: 10
  eval_strategy: steps
  eval_steps: 10
  save_steps: 1000
  gradient_accumulation_steps: 1